### ISSUE TITLE
スーパーユーザー作成時にエラーがでる

### ISSUE THREAD

**Issue by yuma283** [tomishima2904/shapley_association_game#26]
`python manage.py createsuperuser`を実行すると以下のようになる
```
Traceback (most recent call last):
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'createsuperuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    settings.INSTALLED_APPS
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/suzukiyuuma/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/suzukiyuuma/shapley_association_game/shapley_association_game/settings.py", line 14, in <module>
    import os, environ
ModuleNotFoundError: No module named 'environ'
```

**Comment by tomishima2904** [comment]
`docker-compose exec web bash`でweb側のコンテナに入ってから`python manage.py createsuperuser`をやってみるのだ

**Comment by tomishima2904** [comment]
`python manage.py 〜`系のコマンドは基本的に`docker-compose exec web bash`してからやると良い

**Comment by yuma283** [comment]
サンクス
できたわ
