### ISSUE TITLE
Tailwindを利用する際の`npm run dev`がうまくいかない

### ISSUE THREAD

**Issue by tomishima2904** [tomishima2904/shapley_association_game#59]
`npm run dev` もとい `npx tailwindcss -i static/css/style.css -o static/css/style_dist.css --watch`が環境開発者以外での環境でうまくいかないらしい

**Comment by tomishima2904** [comment]
今はdocker-composeでtailwindの環境も追加してみようと試みている。

**Comment by tomishima2904** [comment]
@yuma283 
```
npm install
```
ってやってみてくれい

**Comment by tomishima2904** [comment]
```
% npx tailwindcss init
node:internal/modules/cjs/loader:410
      throw err;
      ^

Error: Cannot find module '/Users/xx/shapley_association_game/node_modules/lilconfig/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:402:19)
    at Module._findPath (node:internal/modules/cjs/loader:644:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1012:27)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Module.require (node:internal/modules/cjs/loader:1092:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/xx/shapley_association_game/node_modules/postcss-load-config/src/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1205:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1259:10)
    at Module.load (node:internal/modules/cjs/loader:1068:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/xx/shapley_association_game/node_modules/lilconfig/package.json',
  requestPath: 'lilconfig'
}

Node.js v19.1.0
```

**Comment by tomishima2904** [comment]
nodeのバージョンを[この](https://zenn.dev/ymasaoka/articles/using-n-for-downgrade-nodejs)方法で18.13.0まで落としてくれ。とりあえずそれで`npm run dev`をやる。それでまだエラー出るんだったらエラーコード貼り付けてくれい。

**Comment by yuma283** [comment]
% node -v
v18.13.0

% npm run dev          

> shapley_association_game@1.0.0 dev
> npx tailwindcss -i static/css/style.css -o static/css/style_dist.css --watch

node:internal/modules/cjs/loader:417
      throw err;
      ^

Error: Cannot find module '/Users/suzukiyuuma/shapley_association_game/node_modules/lilconfig/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:409:19)
    at Module._findPath (node:internal/modules/cjs/loader:651:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/suzukiyuuma/shapley_association_game/node_modules/postcss-load-config/src/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/suzukiyuuma/shapley_association_game/node_modules/lilconfig/package.json',
  requestPath: 'lilconfig'
}

Node.js v18.13.0

**Comment by yuma283** [comment]
相変わらずのエラーが出る

**Comment by tomishima2904** [comment]
じゃあ`npm install lilconfig`で

**Comment by yuma283** [comment]
% npm install lilconfig

up to date, audited 68 packages in 2s

15 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 % npm run dev

> shapley_association_game@1.0.0 dev
> npx tailwindcss -i static/css/style.css -o static/css/style_dist.css --watch

node:internal/modules/cjs/loader:417
      throw err;
      ^

Error: Cannot find module '/Users/suzukiyuuma/shapley_association_game/node_modules/lilconfig/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:409:19)
    at Module._findPath (node:internal/modules/cjs/loader:651:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1025:27)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/suzukiyuuma/shapley_association_game/node_modules/postcss-load-config/src/index.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/suzukiyuuma/shapley_association_game/node_modules/lilconfig/package.json',
  requestPath: 'lilconfig'
}

Node.js v18.13.0

**Comment by yuma283** [comment]
特にlilconfigに追加されたファイルもなく、同じエラーが出てしまう...

**Comment by tomishima2904** [comment]
まじかあ笑

**Comment by yuma283** [comment]
どうすればいいんだ笑
tomiの環境にもnode_modules/lilconfig/dist/index.jsはないんだっけ？

**Comment by tomishima2904** [comment]
ないぜ

**Comment by yuma283** [comment]
そのファイルだけ送れる？

**Comment by yuma283** [comment]
distファイル

**Comment by tomishima2904** [comment]
一応送れるがそっちもあると思うぞ

ディレクトリの構成は二人とも同じで、`node_modules/lilconfig/dist/index.js`は存在するから、おそらくパスが通ってないとかそういう関係だと思う

**Comment by tomishima2904** [comment]
[ここ](https://github.com/tomishima2904/shapley_association_game/tree/develop/1/node_modules/lilconfig)にlilconfigはあるぞ。でも`develop/1`ブランチの内容反映させているから、そっちにもあるはず。

**Comment by tomishima2904** [comment]
ん？ないか

**Comment by yuma283** [comment]
ないのだ

**Comment by tomishima2904** [comment]
あー俺が.gitignoreで`dist`ファイル無視してたわ笑

**Comment by yuma283** [comment]
ほんとや笑
じゃこっちではずしといていいか？

**Comment by tomishima2904** [comment]
俺が外したバージョンを新しくあげるからそれをプルしたほうがいいかも

**Comment by yuma283** [comment]
おけい

**Comment by tomishima2904** [comment]
`develop/1`をプルしてから、`npm run dev`とかやってみてくれい

**Comment by tomishima2904** [comment]
[これ](https://qiita.com/growsic/items/b2965c0ba3b0aaae1ff8)によると`node_modules`って本来はgitで管理しなくていいらしい。
だから、`node_modules`ディレクトリ消して、`npm install`ってやればうまくいくかなあと思っている。

**Comment by yuma283** [comment]
やってみるわ

**Comment by yuma283** [comment]
きた、できた
