### ISSUE TITLE
環境構築時のDockerに関するエラー

### ISSUE THREAD

**Issue by ttoitt** [tomishima2904/shapley_association_game#65]
`docker-compose up -d db`をするとdocker-composeできないと言われる

```      
WARNING: The MYSQL_DATABASE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_USER variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_PASSWORD variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker\api\client.py", line 214, in _retrieve_server_version
  File "docker\api\daemon.py", line 181, in version
  File "docker\utils\decorators.py", line 46, in inner
  File "docker\api\client.py", line 237, in _get
  File "requests\sessions.py", line 543, in get
  File "requests\sessions.py", line 530, in request
  File "requests\sessions.py", line 643, in send
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 670, in urlopen
  File "urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1255, in request
  File "http\client.py", line 1301, in _send_request
  File "http\client.py", line 1250, in endheaders
  File "http\client.py", line 1010, in _send_output
  File "http\client.py", line 950, in send
  File "docker\transport\npipeconn.py", line 32, in connect
  File "docker\transport\npipesocket.py", line 23, in wrapped
  File "docker\transport\npipesocket.py", line 72, in connect
  File "docker\transport\npipesocket.py", line 52, in connect
pywintypes.error: (2, 'CreateFile', '指定されたファイルが見つかりません。')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 81, in main
  File "compose\cli\main.py", line 200, in perform_command
  File "compose\cli\command.py", line 60, in project_from_options
  File "compose\cli\command.py", line 152, in get_project
  File "compose\cli\docker_client.py", line 41, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "docker\api\client.py", line 197, in __init__
  File "docker\api\client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', '指定されたファイルが見つかりません。')
[19464] Failed to execute script docker-compose
```

**Comment by tomishima2904** [comment]
`.env`ファイルを作成してみてくれ。`.env`の内容はgoogle docsの内容をコピペすると良い。
discordからgoogle docsに飛べるリンクがあると思う

**Comment by ttoitt** [comment]
ありがとう！
やってみる。
Qiitaの記事を見返したところ、SECRET_KEYのところがよく理解できていなくて適当にやってたから、それかもしれない。

**Comment by tomishima2904** [comment]
ちなみに、このエラーは`SECRET_KEY`とかがちゃんと定義されていないっていうエラーなんだけど、`.env`に`SECRET_KEY`とか`MYSQL_USER`を定義してあるので、`.env`を作成するとちゃんとそれらの**環境変数**が読み込めるようになるという仕組み

**Comment by ttoitt** [comment]
.envを更新した後は、DB構築にあるコマンドを実行していけばいいん？

**Comment by tomishima2904** [comment]
そう

**Comment by tomishima2904** [comment]
masterじゃくなくてdevelop/1ブランチが最新で開発してるから、そっちのreadmeを参照するとよい

**Comment by tomishima2904** [comment]
@ttoitt 

# 環境構築の手順

1. クローンしてGithub上のディレクトリをそっくりそのままローカルの環境に落とし込む
`git clone git@github.com:tomishima2904/shapley_association_game.git`
2. `.env`ファイルを作成して、google docsの内容をコピペする. `.env`を置く階層は`manage.py`と同階層.

ここからは`readme`の環境構築を順当にやっていけばいけると思う。
つまづいたら、エラーコードを貼って教えてくれい。
